In [ ]:
import pandas as pd

In [22]:
customers = pd.read_csv('../data/raw/customers.csv')

In [23]:
customers.head()

   customer_id  first_name       city    segment signup_date
0            1  Customer_1    Dresden  Corporate  2024-02-01
1            2  Customer_2    Cologne   Consumer  2025-12-17
2            3  Customer_3    Leipzig   Consumer  2024-04-04
3            4  Customer_4  Frankfurt   Consumer  2023-03-02
4            5  Customer_5    Dresden   Consumer  2024-01-04

In [24]:
customers.columns

Index(['customer_id', 'first_name', 'city', 'segment', 'signup_date'], dtype='str')

In [26]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5001 non-null   int64
 1   first_name   5001 non-null   str
 2   city         5000 non-null   str
 3   segment      5000 non-null   str
 4   signup_date  5001 non-null   str
dtypes: int64(1), str(4)
memory usage: 195.5 KB

In [27]:
customers['customer_id'].duplicated().sum()

np.int64(1)

In [28]:
customers.head()

   customer_id  first_name       city    segment signup_date
0            1  Customer_1    Dresden  Corporate  2024-02-01
1            2  Customer_2    Cologne   Consumer  2025-12-17
2            3  Customer_3    Leipzig   Consumer  2024-04-04
3            4  Customer_4  Frankfurt   Consumer  2023-03-02
4            5  Customer_5    Dresden   Consumer  2024-01-04

In [29]:
customers[customers['customer_id'].duplicated(keep=False)]

      customer_id     first_name        city   segment signup_date
999          1000  Customer_1000  Düsseldorf  Consumer  2024-07-10
5000         1000  Customer_1000  Düsseldorf  Consumer  2024-07-10

In [30]:
customers.duplicated().sum()

np.int64(1)

In [34]:
customers.isnull().sum()

customer_id    0
first_name     0
city           1
segment        1
signup_date    0
dtype: int64

In [33]:
customers[customers.isnull().any(axis=1)]

     customer_id    first_name     city   segment signup_date
117          118  Customer_118      NaN  Consumer  2023-12-31
842          843  Customer_843  Dresden       NaN  2023-03-04

In [32]:
customers['customer_id'].nunique()

5000

In [35]:
products = pd.read_csv('../data/raw/products.csv')

In [38]:
products.head()

   product_id product_name  category  unit_price
0           1  Product_001      Home       35.24
1           2  Product_002     Books       24.59
2           3  Product_003  Clothing       58.74
3           4  Product_004    Sports       28.13
4           5  Product_005    Beauty       22.34

In [39]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    int64
 1   product_name  100 non-null    str
 2   category      99 non-null     str
 3   unit_price    99 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 3.3 KB

In [42]:
products[products.isnull().any(axis=1)]

    product_id product_name category  unit_price
18          19  Product_019      NaN       34.41
54          55  Product_055   Beauty         NaN

In [43]:
products['product_id'].nunique()

100

In [44]:
orders = pd.read_csv('../data/raw/orders.csv')
orders.head()

   order_id  customer_id  order_date     status payment_method
0         1         4582  2025-10-16  Completed           Card
1         2         1461  2024-04-08  Completed  Bank Transfer
2         3         3888  2024-08-12  Completed  Bank Transfer
3         4          293  2024-03-15  Completed         PayPal
4         5         1644  2025-12-10  Completed           Card

In [45]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20001 entries, 0 to 20000
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        20001 non-null  int64
 1   customer_id     20001 non-null  int64
 2   order_date      20001 non-null  str
 3   status          20001 non-null  str
 4   payment_method  20000 non-null  str
dtypes: int64(2), str(3)
memory usage: 781.4 KB

In [46]:
orders[orders.isnull().any(axis=1)]

      order_id  customer_id  order_date     status payment_method
1234      1235          239  2024-05-06  Completed            NaN

In [47]:
orders['order_id'].nunique()

20000

In [48]:
orders[orders['order_id'].duplicated(keep=False)]

       order_id  customer_id  order_date     status payment_method
5000       5001         4546  2025-01-11  Completed           Card
20000      5001         4546  2025-01-11  Completed           Card

In [49]:
orders[orders['payment_method'].isnull()]

      order_id  customer_id  order_date     status payment_method
1234      1235          239  2024-05-06  Completed            NaN

In [50]:
orders['status'].value_counts()

status
Completed    18005
Cancelled     1396
Returned       599
completed        1
Name: count, dtype: int64

In [51]:
order_items = pd.read_csv('../data/raw/order_items.csv')

In [52]:
order_items.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1     13163          30         1       24.01
1              2      5149          73         1       60.13
2              3     14210          86         3        5.88
3              4     19496          33         2       49.56
4              5     19369          99         1       48.94

In [53]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 55001 entries, 0 to 55000
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  55001 non-null  int64
 1   order_id       55001 non-null  int64
 2   product_id     55001 non-null  int64
 3   quantity       55001 non-null  int64
 4   unit_price     54471 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 2.1 MB

In [54]:
order_items['order_item_id'].nunique()

55000

In [55]:
order_items[order_items['order_item_id'].duplicated(keep=False)]

       order_item_id  order_id  product_id  quantity  unit_price
1000            1001     17632           5         4       20.92
55000           1001     17632           5         4       20.92

In [57]:
order_items['quantity'].value_counts().sort_index()

quantity
-2        1
 0        1
 1    30102
 2    13879
 3     6574
 4     3372
 5     1072
Name: count, dtype: int64

In [ ]:
order_items['order_id'].nunique()